# Generated by Django 5.1.4 on 2025-01-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dbr_payment', '0004_alter_company_options_company_telegram_chat_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name_plural': 'Companies'},
        ),
        migrations.RemoveField(
            model_name='company',
            name='telegram_chat_id',
        ),
    ]
