# Generated by Django 5.1.4 on 2025-01-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dbr_payment', '0005_alter_company_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Telegram Chat ID'),
        ),
    ]
